name: Test SonarQube Connectivity

on: 
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub

jobs:
  connectivity_test:
    runs-on: self-hosted
    steps:
      - name: Check connectivity with ping
        run: ping -n 4 192.168.98.35

      - name: Test connection to SonarQube API
        run: |
          Invoke-WebRequest -Uri "http://192.168.98.35:9000/api/system/status" -UseBasicParsing

      - name: Test connection with authentication
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          Invoke-WebRequest -Uri "http://192.168.98.35:9000/api/authentication/validate" -Headers @{"Authorization"="Bearer $env:SONAR_TOKEN"} -UseBasicParsing
